// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/16/2026, 4:16:35 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["D:/Project/Training/VueJS/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Project/Training/VueJS/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Project/Training/VueJS/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Project/Training/VueJS/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Project/Training/VueJS/plugins/**/*.{js,ts,mjs}","D:/Project/Training/VueJS/composables/**/*.{js,ts,mjs}","D:/Project/Training/VueJS/utils/**/*.{js,ts,mjs}","D:/Project/Training/VueJS/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Project/Training/VueJS/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Project/Training/VueJS/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Project/Training/VueJS/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;